apiVersion: v1
kind: Service
metadata:
  labels:
    app: radiant-keycloak
  name: radiant-keycloak
spec:
  type: LoadBalancer
  ports:
    - name: "8282"
      port: 8282
      targetPort: 8282
  selector:
    app: radiant-keycloak
