fullnameOverride: radiant-polaris

managementService:
  type: LoadBalancer
  clusterIP: # To allow kubernetes to assign the IP address

service:
  name: radiant-polaris
  type: LoadBalancer

features:
  SUPPORTED_CATALOG_STORAGE_TYPES:
    - S3
  ALLOW_SETTING_S3_ENDPOINTS: true

authentication:
  tokenBroker:
    type: symmetric-key
    secret:
      name: radiant-polaris-token-broker-secret

persistence:
  type: relational-jdbc
  relationalJdbc:
    secret:
      name: radiant-polaris-persistence-secret
      username: username
      password: password
      jdbcUrl: jdbcUrl

extraEnv:
  - name: AWS_REGION
    value: us-east-1
  - name: AWS_ACCESS_KEY_ID
    value: admin
  - name: AWS_SECRET_ACCESS_KEY
    value: password
  - name: AWS_ENDPOINT_URL
    value: "http://radiant-minio:9000"
  - name: AWS_ALLOW_HTTP
    value: "true"