apiVersion: v1
kind: Service
metadata:
  labels:
    app: radiant-iceberg-rest
  name: radiant-iceberg-rest
spec:
  type: LoadBalancer
  ports:
    - name: "8181"
      port: 8181
      targetPort: 8181
  selector:
    app: radiant-iceberg-rest
