FROM --platform=linux/amd64 public.ecr.aws/amazonlinux/amazonlinux:2023.7.20250609.0

USER root
ENV PYTHON_VERSION=3.12

# Install build dependencies, required for MySQL client on MWAA
RUN dnf install -y mariadb105-devel
RUN dnf groupinstall -y "Development Tools" && \
    dnf install -y \
        bzip2-devel \
        curl-devel \
        libcurl-devel \
        openssl-devel \
        zlib-devel \
        xz-devel \
        libpsl-devel \
        python${PYTHON_VERSION} \
        python${PYTHON_VERSION}-pip \
        python${PYTHON_VERSION}-devel \
        pkgconfig && \
    dnf clean all

# Install uv
RUN curl -LsSf https://astral.sh/uv/install.sh | sh
ENV PATH="/root/.local/bin:$PATH"

# Create a virtual environment using uv
RUN uv venv --python python${PYTHON_VERSION} /home/airflow/.venv/radiant

ENV VIRTUAL_ENV=/home/airflow/.venv/radiant
ENV PATH="/home/airflow/.venv/radiant/bin:$PATH"

RUN python${PYTHON_VERSION} -m venv /home/airflow/.venv/radiant && \
    /home/airflow/.venv/radiant/bin/pip install wheel --no-cache-dir

# Copy requirements and install dependencies with uv
COPY requirements-deps.txt /home/airflow/.venv/radiant/requirements.txt
COPY constraints-3.12.txt  /usr/local/airflow/plugins/constraints-3.12.txt
RUN uv pip compile /home/airflow/.venv/radiant/requirements.txt --output-file /home/airflow/.venv/radiant/requirements.lock.txt

RUN /home/airflow/.venv/radiant/bin/pip wheel -w /home/airflow/.venv/radiant/wheels -r /home/airflow/.venv/radiant/requirements.lock.txt
RUN cp /usr/local/airflow/plugins/constraints-3.12.txt /home/airflow/.venv/radiant/wheels/constraints-3.12.txt
RUN zip -j /home/airflow/.venv/radiant/plugins.zip /home/airflow/.venv/radiant/wheels/*.whl /home/airflow/.venv/radiant/wheels/constraints-3.12.txt
