---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: radiant-api
  name: radiant-api
spec:
  type: LoadBalancer
  ports:
    - port: 8090
      protocol: TCP
      targetPort: 8090
  selector:
    app: radiant-api