apiVersion: batch/v1
kind: Job
metadata:
  name: radiant-minio-bucket-init-job
spec:
  template:
    spec:
      restartPolicy: OnFailure
      initContainers:
        - name: wait-for-minio
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until nc -z radiant-minio 9000; do
                echo "Waiting for MinIO..."
                sleep 2
              done
      containers:
        - name: create-bucket
          image: minio/mc:RELEASE.2024-10-29T15-34-59Z
          command:
            - sh
            - -c
            - |
              mc alias set myminio http://radiant-minio:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD && \
              mc mb -p myminio/starrocks || echo "Bucket starrocks already exists"
              mc mb -p myminio/warehouse || echo "Bucket warehouse already exists"
              mc mb -p myminio/vcf || echo "Bucket vcf already exists"
          env:
            - name: MINIO_ROOT_USER
              value: "admin"
            - name: MINIO_ROOT_PASSWORD
              value: "password"
