apiVersion: v1
kind: Service
metadata:
  labels:
    app: radiant-minio
  name: radiant-minio
spec:
  type: LoadBalancer
  ports:
    - name: "9001"
      port: 9001
      targetPort: 9001
    - name: "9000"
      port: 9000
      targetPort: 9000
  selector:
    app: radiant-minio
