apiVersion: v1
kind: Service
metadata:
  name: radiant-polaris
  labels:
    app: radiant-polaris
spec:
  type: LoadBalancer
  selector:
    app: radiant-polaris
  ports:
    - port: 8181
      targetPort: 8181
      protocol: TCP
