apiVersion: v1
kind: Secret
metadata:
  name: radiant-polaris-persistence-secret
type: Opaque
data:
  
  # echo -n "postgres" | base64  
  username: cG9zdGdyZXM=
  password: cG9zdGdyZXM=

  # echo -n "jdbc:postgresql://postgres:5432/polaris_catalog" | base64
  jdbcUrl: amRiYzpwb3N0Z3Jlc3FsOi8vcG9zdGdyZXM6NTQzMi9wb2xhcmlzX2NhdGFsb2c=
