apiVersion: v1
kind: PersistentVolume
metadata:
  name: radiant-dags-pv
  labels:
    app: airflow
    type: radiant-dags
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /opt/airflow/dags
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radiant-dags-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: airflow
      type: radiant-dags