apiVersion: v1
kind: Service
metadata:
  labels:
    app: radiant-starrocks-fe
  name: radiant-starrocks-fe
spec:
  type: LoadBalancer
  ports:
    - name: "8030"
      port: 8030
      targetPort: 8030
    - name: "9020"
      port: 9020
      targetPort: 9020
    - name: "9030"
      port: 9030
      targetPort: 9030
  selector:
    app: radiant-starrocks-fe

